const Products = [
        {
            "storeProductId": 1764,
            "productId": '1',
            "pname": "Fresh Tomato",
            "pUnit": "1Kg",
            "pimage": "http://www.way2door.com/images/products/tamato.jpg",
            "pdescription": "",
            "price": 60,
            "sellPrice": 50,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:11:45",
            "updated_at": "2021-11-13 15:04:07",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1765,
            "productId": '2',
            "pname": "Potato Old",
            "pUnit": "1 Kg",
            "pimage": "http://www.way2door.com/images/products/potato.jpg",
            "pdescription": "",
            "price": 30,
            "sellPrice": 20,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:11:45",
            "updated_at": "2021-11-13 15:04:08",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1766,
            "productId": '3',
            "pname": "Onion",
            "pUnit": "1Kg",
            "pimage": "http://www.way2door.com/images/products/onion.jpg",
            "pdescription": "",
            "price": 50,
            "sellPrice": 30,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:11:45",
            "updated_at": "2021-11-13 15:04:09",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1774,
            "productId": '315',
            "pname": "Green Chilli",
            "pUnit": "250 gm",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Chilli.jpg",
            "pdescription": "",
            "price": 20,
            "sellPrice": 15,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:38:05",
            "updated_at": "2021-11-13 17:24:04",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1777,
            "productId": '8',
            "pname": "Garlic (Lehsun)",
            "pUnit": "250 gm",
            "pimage": "http://www.way2door.com/images/products/garlic_lehsun.jpg",
            "pdescription": "",
            "price": 60,
            "sellPrice": 40,
            "availableQuanity": 0,
            "is_available": 0,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:39:58",
            "updated_at": "2021-11-13 17:28:47",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1779,
            "productId": '334',
            "pname": "Green Capsicum ( Shimla Mirch )",
            "pUnit": "250 gm",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Capsicum-way2door.jpg",
            "pdescription": "",
            "price": 40,
            "sellPrice": 20,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:42:05",
            "updated_at": "2021-11-13 17:24:09",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1782,
            "productId": '327',
            "pname": "Carrot",
            "pUnit": "1 Kg",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Orange Carrot-way2door.jpg",
            "pdescription": "",
            "price": 50,
            "sellPrice": 40,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:44:37",
            "updated_at": "2021-11-13 17:27:07",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1788,
            "productId": '9',
            "pname": "Coriander",
            "pUnit": "250 gm",
            "pimage": "http://www.way2door.com/images/products/coriander.jpg",
            "pdescription": "",
            "price": 30,
            "sellPrice": 10,
            "availableQuanity": 0,
            "is_available": 0,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:46:49",
            "updated_at": "2021-11-13 17:24:16",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1793,
            "productId": '175',
            "pname": "Pomegranate (Anaar)",
            "pUnit": "1 Kg",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Pomegranate (Anaar).jpg",
            "pdescription": "",
            "price": 180,
            "sellPrice": 155,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Fruits",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 18:50:31",
            "updated_at": "2021-11-13 04:21:22",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1800,
            "productId": '39',
            "pname": "Cabbage",
            "pUnit": "1 unit",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cabbage-way2door.jpg",
            "pdescription": "",
            "price": 35,
            "sellPrice": 30,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 19:06:49",
            "updated_at": "2021-11-13 17:34:35",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1802,
            "productId": '66',
            "pname": "Cauliflower",
            "pUnit": "1 unit",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Cauliflower.jpg",
            "pdescription": "",
            "price": 50,
            "sellPrice": 30,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Vegetables",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-09 19:07:19",
            "updated_at": "2021-11-13 17:34:21",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1811,
            "productId": '34',
            "pname": "Guava ( Amrud )",
            "pUnit": "1Kg",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Guava.jpg",
            "pdescription": "",
            "price": 65,
            "sellPrice": 60,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Fruits",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-10 14:38:48",
            "updated_at": "2021-11-13 04:30:33",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1816,
            "productId": '30',
            "pname": "Papaya 1 KG",
            "pUnit": "1 unit",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Papaya-way2door.jpg",
            "pdescription": "",
            "price": 60,
            "sellPrice": 55,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Fruits",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-10 14:39:19",
            "updated_at": "2021-11-13 04:16:48",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 1819,
            "productId": '224',
            "pname": "Green Coconut",
            "pUnit": "1 unit",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Green Coconut-way@door.jpg",
            "pdescription": "",
            "price": 50,
            "sellPrice": 40,
            "availableQuanity": 0,
            "is_available": 0,
            "mainCat": null,
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2018-09-10 14:56:49",
            "updated_at": "2021-11-13 04:39:42",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2608,
            "productId": '229',
            "pname": "Banana",
            "pUnit": "12 unit",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Yellaki (Kathali Kala) Banana-way@door.jpg",
            "pdescription": "",
            "price": 60,
            "sellPrice": 50,
            "availableQuanity": 0,
            "is_available": 1,
            "mainCat": "Fresh_Fruits",
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:27:13",
            "updated_at": "2021-11-13 04:28:16",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2609,
            "productId": '25',
            "pname": "Kashmiri Apple",
            "pUnit": "1 Kg",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Kashmiri Apple-way2door.jpg",
            "pdescription": "",
            "price": 140,
            "sellPrice": 130,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": null,
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:29",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2610,
            "productId": '171',
            "pname": "Shimla Apple",
            "pUnit": "1 Kg",
            "pimage": "http://www.way2door.com/AllProducts/fruits_and_vegetables/Shimla Apple.jpg",
            "pdescription": "",
            "price": 170,
            "sellPrice": 165,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": null,
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:30",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2611,
            "productId": '1001',
            "pname": "Eggs",
            "pUnit": "12 pcs",
            "pimage": "https://st.depositphotos.com/1782880/1763/i/600/depositphotos_17631741-stock-photo-white-egg-group.jpg",
            "pdescription": "",
            "price": 100,
            "sellPrice": 85,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": 'Fresh_Non_Veg',
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:30",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2612,
            "productId": '1002',
            "pname": "Amul Paneer",
            "pUnit": "200 gm",
            "pimage": "https://www.bigbasket.com/media/uploads/p/l/40096747_7-amul-malai-fresh-paneer.jpg",
            "pdescription": "",
            "price": 100,
            "sellPrice": 80,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": 'Dairy_Products',
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:30",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2613,
            "productId": '1003',
            "pname": "Chicken",
            "pUnit": "1 kg",
            "pimage": "https://dao54xqhg9jfa.cloudfront.net/OMS-Category/34466dbd-a515-edd1-3e99-05000f217cb6/original/Chicken_(2).png",
            "pdescription": "",
            "price": 450,
            "sellPrice": 400,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": 'Fresh_Non_Veg',
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:30",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500,
            "is_in_cart": false,
            "quantity": 0
        },
        {
            "storeProductId": 2614,
            "productId": '1004',
            "pname": "California Almonds",
            "pUnit": "500 gm",
            "pimage": "https://images.wellcurve.in/wp-content/uploads/2022/01/Untitled-design-12-1-6-600x600.jpg",
            "pdescription": "",
            "price": 420,
            "sellPrice": 372,
            "availableQuanity": 1,
            "is_available": 1,
            "mainCat": 'Dry_Fruits',
            "subMainCat": null,
            "subCat": null,
            "is_active": 1,
            "featured_product": 1,
            "storeId": 26,
            "created_at": "2021-11-13 04:31:52",
            "updated_at": "2021-11-13 04:32:30",
            "deliveryCharge": 40,
            "storeName": "Lucknow Veg Express",
            "freeDeliveryMinOrderAmount": 500
        }
        
    ];

export default Products;